version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:57"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "devsecops"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:57"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "security"
