kkversion: 2
updates:
  # Analyse quotidienne des dépendances Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:15"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "devsecops"
    reviewers:
      - "youssouf95"
    commit-message:
      prefix: "chore"
      include: "scope"
  # Analyse quotidienne des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "security"


