version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"   # Vérification chaque semaine
      time: "14:15"
      timezone: "Europe/Paris"
     open-pull-requests-limit: 5
